// <auto-generated />
using System;
using Bereschi_Gabriel_Depozit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bereschi_Gabriel_Depozit.Migrations
{
    [DbContext(typeof(Bereschi_Gabriel_DepozitContext))]
    [Migration("20220217002952_Updates")]
    partial class Updates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bereschi_Gabriel_Depozit.Models.Depozit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacitate")
                        .HasColumnType("int");

                    b.Property<int>("IDProprietar")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProprietarID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProprietarID");

                    b.ToTable("Depozit");
                });

            modelBuilder.Entity("Bereschi_Gabriel_Depozit.Models.Produs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Depozit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Greutate")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vanzator")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("Bereschi_Gabriel_Depozit.Models.Proprietar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Proprietar");
                });

            modelBuilder.Entity("Bereschi_Gabriel_Depozit.Models.Depozit", b =>
                {
                    b.HasOne("Bereschi_Gabriel_Depozit.Models.Proprietar", "Proprietar")
                        .WithMany("Depozite")
                        .HasForeignKey("ProprietarID");
                });
#pragma warning restore 612, 618
        }
    }
}
